[project]
name = "evidently-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "evidently>=0.7.17",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
